'use-strict';

/**
 * @fileoverview
 * This is a wrapper module to <em>promisify</em> the email verification link
 * generation and the sending of these links by email.
 *
 * @summary verification link generation service.
 * @module ./VerificationEmailService.js
 * @export generate
 * @author Mario Moro Hernández
 * @license None
 * @version 0.0.alpha
 */

module.exports = {
    /**
     * This is a wrapper function to generate an verification link and send it
     * by email to the user. The links generated by this function expire after
     * four hours.
     * 
     * @param {Object} user - an object containing name, username and email for
     *                        the receiver user.
     * @return {Promise} - a promise with the result of the sending email operation.
     */
    generate: function (user) {
	return new Promise(function (resolve, reject) {
	    //generate link
	    var token = JWTService.issueToken({user: user.userName}, // payload
					      undefined, // secret (undefined, so the service uses the default)
					      {algorithm: sails.config.jwtSettings.algorithm, // options
					       expiresIn: 4 * 60 * 60, // <---- Link expires in 4 hours
					       issuer: sails.config.jwtSettings.issuer,
					       audience: sails.config.jwtSettings.audience});
	    
	    var link = 'http://localhost:1337/user/verify-profile?authorization=' + token +
	     '&username=' + user.userName +
	     '&firstname=' + user.firstName +
	     '&lastname=' + user.lastName +
	     '&email=' + user.email;
	    
	    // Send verification email
	    SendgridService.send({
		to: [{name: user.firstName + ' ' + user.lastName, email: user.email}],
		from: {name : 'admin', email : 'noreply@someservice.ml'},
		subject: 'Please verify your account',
		body: {text: '<H1>Verify your account</H1><br>' +
		       '<p>Click on this link to verify your account:<br>' +
		       link + '</p>',
		       format: 'html'}
	    }, function(err, data) {
		if (err) return reject(err);
		return resolve('Sent verification link to the specified email account');
	    });
	});
    }
};
